### ISSUE TITLE
Can't build using README instructions

### ISSUE THREAD

**Issue by twouters** [jcjones/ct-sql#3]
`go get github.com/jcjones/ct-sql/cmd/ct-sql` fails with the following error, not sure if this is a global issue or something with my setup.

```
# github.com/jcjones/ct-sql/cmd/ct-sql
go/src/github.com/jcjones/ct-sql/cmd/ct-sql/main.go:84: not enough arguments in call to client.New
go/src/github.com/jcjones/ct-sql/cmd/ct-sql/main.go:84: multiple-value client.New() in single-value context
```

**Comment by jcjones** [comment]
Looks like it's gotten behind Google's CT client code again. I'll patch it ASAP.

**Comment by jcjones** [comment]
Fixed in 506c02a6e6a35e3fb46c4428232c61c3d4d508f5

**Comment by jcjones** [comment]
Also - thanks for the heads up! 👍

**Comment by twouters** [comment]
Thanks !
